### ISSUE TITLE
(removed)

### ISSUE THREAD

**Issue by cedricfrancoys** [romaniso/easy-peasy-platform#6]

**Comment by romaniso** [comment]
Hi Cedric,

Thanks for reaching out to me and for the star :)

I appreciate your attention and will gladly check out your project as well.
Sorry for not getting back to you sooner, but it is vacation time, so
unfortunately I am only partially available at this time. I will find some
time and leave my feedback, of course ;)

Keep in touch,
Roman

sob., 20 lip 2024 o 10:39 Cédric Françoys ***@***.***>
napisał(a):
